### ISSUE TITLE
Serve Bookdown Produced Document

### ISSUE THREAD

**Issue by GrayAlex49** [rstudio/shiny-server#488]
According to the [shiny server docs][1], an r-markdown with an index (like a bookdown doc) should be served by shiny if its in the /srv/shiny-server/ folder.

I cloned the [sample bookdown example][2] and mounted it to a shiny server.

Dockerfile:
```
FROM rocker/shiny-verse:4.0.5

RUN install2.r -e bookdown
```

Docker Compose:
```
version: '3.8'
services:

    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: bookdown_test
        container_name: bookdown_test
        restart: always
        #user: 'root'
        volumes:
            - ./bookdown-demo:/srv/shiny-server/book
        ports:
            - '80:3838'
```
This should serve the book at localhost/book however I only get a blank page and stdout message:
```
bookdown_test  | processing file: index.Rmd
bookdown_test  | output file: /tmp/shiny/rmarkdown/1dd8e4d901d7b5552128fdca39407670/index.knit.md
bookdown_test  |
bookdown_test  |
bookdown_test  | Output created: section-prerequisites.html
```
The file that it creates is not what it should create either.
[![enter image description here][3]][3]

How can I utilize shiny server to effectively serve app documentation? It seems like this should work. 

  [1]: https://docs.rstudio.com/shiny-server/#r-markdown
  [2]: https://github.com/rstudio/bookdown-demo
  [3]: https://i.stack.imgur.com/4eHJw.png
